# .github/workflows/advanced-ui-testing.yaml
name: Advanced Selenium UI Tests

on:
  pull_request:
    branches:
     - master

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test against'
        required: true
        default: 'staging'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  selenium-matrix-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chrome, firefox]
        resolution: 
          - { name: 'desktop-full', width: 1920, height: 1080 }
          - { name: 'laptop', width: 1366, height: 768 }
          - { name: 'mobile', width: 375, height: 667 }
      fail-fast: false  # Continue other jobs even if one fails
    
    name: Test ${{ matrix.browser }} - ${{ matrix.resolution.name }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        repository: hamad-fyad/OllamaUITesting #TODO: Replace with your actual repository and do the token setup
        token: ${{ secrets.UI_TESTING_GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Chrome and ChromeDriver
      if: matrix.browser == 'chrome'
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install Firefox and GeckoDriver
      if: matrix.browser == 'firefox'
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
        
    - name: Run Selenium tests
      env:
        HEADLESS: true
        BROWSER: ${{ matrix.browser }}
        SCREEN_WIDTH: ${{ matrix.resolution.width }}
        SCREEN_HEIGHT: ${{ matrix.resolution.height }}
        OLLAMA_URL: http://54.246.63.185:3000/ # TODO: Replace with actual Ollama URL
        TEST_NAME: ${{ matrix.browser }}-${{ matrix.resolution.name }}
      run: |
        pytest tests/ -v --tb=short

    - name: Upload Allure results as artifact
      uses: actions/upload-artifact@v4
      if: always()  # Upload even if tests fail
      with:
        name: allure-results-${{ matrix.browser }}-${{ matrix.resolution.name }}
        path: allure-results/
        retention-days: 30

  allure-report:
    runs-on: ubuntu-latest
    needs: selenium-matrix-tests
    if: always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download all Allure results
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results-*
          path: allure-results-downloaded
          merge-multiple: false

      - name: Merge all results into single directory
        run: |
          mkdir -p allure-results
          for dir in allure-results-downloaded/*/; do
            if [ -d "$dir" ]; then
              cp -r "$dir"* allure-results/ 2>/dev/null || true
            fi
          done
          
      - name: Generate and Deploy Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history
          keep_reports: 20
   
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.UI_TESTING_GITHUB_TOKEN }}
          publish_dir: allure-history